- name: Create Ghost
  kubernetes.core.k8s:
    state: present
    src: Kubernets/ghost-deployment.yml

- name: Service Ghost
  kubernetes.core.k8s:
    state: present
    src: Kubernets/ghost-service.yml

- name: Get MySQL Pod Name
  register: ola2
  shell: kubectl get pods --output yaml

- name: Get MySQL Pod Name 2
  set_fact:
   abc: "{{ ola2.stdout_lines[136] | regex_replace('\\ +name:\\ ')}}"

- name: Update Admin in MySQL
  register: ola2
  shell: kubectl exec -it {{abc}} -- bash -c "mysql -u ghostuser -pola ghost -e \"update users set name='ascn', password='\\\$2b\\\$10\\\$eALJbjSd4uptSAQz3XVFMeTwmFZCah7TalSSDkMl6Kh0qsZJ2Sdzm', email='ascn@example.com', status='active' where id=1;\""
  
- name: Get Ghost IP
  register: ola
  shell: kubectl get service ghost-service --output yaml

- name: Get Ghost IP 2
  set_fact:
   ghost_ip: "{{ ola.stdout_lines[-1] | regex_search('\\d+\\.\\d+\\.\\d+\\.\\d+')}}"

