- name: Service Ghost
  kubernetes.core.k8s:
    state: present
    src: Kubernets/ghost-service.yml

- name: Wait for Ghost Service External IP
  shell: "kubectl get services ghost-service -o wide | awk '{ print $4}' |  grep -v EXT"
  register: k_ext_ip
  until: k_ext_ip.stdout[0].isdigit() != False
  retries: 12
  delay: 10

- name: Get Ghost IP
  kubernetes.core.k8s_info:
    kind: Service
    label_selectors:
      - app = ghost
  register: ghost_service

- name: Get Ghost IP 2
  set_fact:
    ghost_ip: "{{ ghost_service.resources[0].status.loadBalancer.ingress[0].ip }}"

- name: Update ghost_ip
  template: src=gcp_template dest=inventory/gcp.yml

- name: Update ghost_deployment.yml
  template: src=ghost_template dest=Kubernets/ghost-deployment.yml

- name: Create Ghost
  kubernetes.core.k8s:
    state: present
    src: Kubernets/ghost-deployment.yml

- name: Get MySQL Pod Name
  kubernetes.core.k8s_info:
    kind: Pod
    label_selectors:
      - app = mysql
  register: mysql_pod

- name: Update Admin in MySQL
  shell: kubectl exec -it {{ mysql_pod.resources[0].metadata.name }} -- bash -c "mysql -u ghostuser -pola ghost -e \"update users set name='ascn', password='\\\$2b\\\$10\\\$eALJbjSd4uptSAQz3XVFMeTwmFZCah7TalSSDkMl6Kh0qsZJ2Sdzm', email='ascn@example.com', status='active' where id=1;\""
  register: update_admin
  until: "update_admin is not failed"
  retries: 12
  delay: 10

- name: Create Dashboard
  shell: "gcloud monitoring dashboards create --config-from-file=roles/ghost_app/dashboards/Ghost_Cluster_Monitor.json"
