- name: Create Ghost
  kubernetes.core.k8s:
    state: present
    src: Kubernets/ghost-deployment.yml

- name: Service Ghost
  kubernetes.core.k8s:
    state: present
    src: Kubernets/ghost-service.yml

- name: Get mysql pod
  register: ola2
  shell: kubectl get pods --output yaml

- name: Get Ghost IP
  set_fact:
   abc: "{{ ola2.stdout_lines[136] | regex_replace('\\ +name:\\ ')}}"

- name: Get mysql pod
  register: ola2
  shell: kubectl exec -it {{abc}} mysql --u ghostuser --p ola -D ghost --e "update users set name='ascn', password='\$2b\$10\$eALJbjSd4uptSAQz3XVFMeTwmFZCah7TalSSDkMl6Kh0qsZJ2Sdzm', email='ascn@example.com', status='active' where id=1;"
  
- name: Get IP
  register: ola
  shell: kubectl get service ghost-service --output yaml

- name: Get Ghost IP
  set_fact:
   ghost_ip: "{{ ola.stdout_lines[-1] | regex_search('\\d+\\.\\d+\\.\\d+\\.\\d+')}}"

