---    
#- name: Create PV
#  kubernetes.core.k8s:
#    state: present
#    src: Kubernets/persistent-volume.yml


- name: Create MySQL
  kubernetes.core.k8s:
    state: present
    src: Kubernets/mysql/mysql-deployment.yml

- name: PVC MySQL
  kubernetes.core.k8s:
    state: present
    src: Kubernets/mysql/mysql-pvc.yml


- name: Service MySQL
  kubernetes.core.k8s:
    state: present
    src: Kubernets/mysql/mysql-service.yml


 